version: '3.9'


services:

  # App auth service
  app-auth:
    build:
      context: pract_spring_auth
      dockerfile: Dockerfile
    ports:
      - '${SPRING_AUTH_DEFAULT_PORT:?error}:${SPRING_DEFAULT_PORT:?error}'
    restart: no
    environment:
      DB_SCHEMA: $DB_SCHEMA
      DB_SERVER: app-db
      DB_DEFAULT_PORT: $DB_DEFAULT_PORT
      DB_LOCAL_USER: $DB_DOCKER_USER
      DB_LOCAL_PASSWORD: $DB_DOCKER_PASSWORD
    networks:
      - backend

  # App backend service
  app-server:
    build:
      context: pract_spring
      dockerfile: Dockerfile
    expose:
      - '${SPRING_DEFAULT_PORT:?error}'
    restart: no
    depends_on:
      app-db:
        condition: service_healthy
    environment:
      DB_SCHEMA: $DB_SCHEMA
      DB_DEFAULT_PORT: $DB_DEFAULT_PORT
      DB_LOCAL_USER: $DB_DOCKER_USER
      DB_LOCAL_PASSWORD: $DB_DOCKER_PASSWORD
      DB_SERVER: app-db
      SPRING_AUTH_SERVER: app-auth
    networks:
      - backend

  # Database service (Mysql)
  app-db:
    build:
      context: database
      dockerfile: Dockerfile
    expose:
      - '${DB_DEFAULT_PORT:?error}'
    restart: no
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_SCHEMA
      MYSQL_USER: $DB_DOCKER_USER
      MYSQL_PASSWORD: $DB_DOCKER_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_DOCKER_ROOT_PASSWORD
    networks:
      - backend


volumes:
  db-data:


networks:
  backend:
    driver: bridge