version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
